version: "3.9"
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata_dev:/var/lib/postgresql/data

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "${API_PORT}:3000"   # 5043 -> 3000 внутрь
    depends_on:
      - db
    volumes:
      - ./server:/app
      - /app/node_modules
    command: yarn start:dev

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "${WEB_PORT}:5173"   # 3043 -> 5173 внутрь
    depends_on:
      - server
    environment:
      - VITE_API_URL=http://localhost:${API_PORT}
    volumes:
      - ./client:/app
      - /app/node_modules
    command: yarn dev --host 0.0.0.0 --port 5173

volumes:
  pgdata_dev:
