version: "3.9"
services:
  db:
    image: postgres:15-alpine
    container_name: ddoser-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: ddoser-server
    restart: always
    ports:
      - "${API_PORT}:3000"
    env_file: .env.prod
    depends_on:
      - db

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://localhost:${API_PORT}
    container_name: ddoser-client
    restart: always
    depends_on:
      - server
    ports:
      - "${WEB_PORT}:80"

volumes:
  pgdata:
